---
title: "p8105_hw3_xz2788"
author: "Xiaoyue Zhang"
date: "10/4/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 1

Load dataset and package

```{r load_dataset_package}
library(p8105.datasets)
library(tidyverse)
```

Look at the data first

```{r overview_data, eval=FALSE}
str(brfss_smart2010)
head(brfss_smart2010)
tail(brfss_smart2010)
View(brfss_smart2010)
```

Tidy the data

```{r tidy_data}
brfss_smart2010_tidy = janitor::clean_names(brfss_smart2010) %>%
  filter(topic == "Overall Health") %>% 
  rename(state = locationabbr, county = locationdesc) %>% 
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor"))
```

Convert the "response" variable into a factor

```{r convert_to_factor}
brfss_smart2010_tidy$response = factor(brfss_smart2010_tidy$response, 
                      levels = c("Excellent", "Very good", "Good", "Fair", "Poor"))
```

## which states were observed at 7 locations

```{r state_at_seven_locations}
brfss_smart2010_tidy %>% 
  group_by(state) %>% 
  summarize(n_location = n_distinct(geo_location)) %>% 
  filter(n_location == 7)
```

There are seven states were observed at 7 locations. These are:
"Connecticut (CT)", "Montana (MT)", "New Hampshire (NH)", "New Mexico (NM)", "Oregon (OR)", "Tennessee (TN)", "Utah (UT)"

## "Spaghetti plot"

```{r spaghetti_plot}
brfss_smart2010_tidy %>% 
  group_by(state, year) %>% 
  summarize(n_obs = sum(sample_size)) %>% 
  ggplot(aes(x = year, y = n_obs)) + 
  geom_line(aes(color = state)) +
  labs(
    title = "Observation plot",
    x = "Year",
    y = "Number of observations"
  )
```

## Making a table

```{r}
filter(brfss_smart2010_tidy, 
       state == "NY",
       year %in% c(2002, 2006, 2010),
       response == "Excellent") %>%
  group_by(year) %>% 
  summarize(sd_prop = sd(data_value),
            mean_prop = mean(data_value)) %>% 
  knitr::kable(digits = 2)
```

## Five-panel plot

```{r}
brfss_smart2010_tidy %>% 
  group_by(state, year, response) %>% 
  summarize(average_prop = mean(data_value)) %>% 
  ggplot(aes(x = year, y = average_prop)) +
  geom_line(aes(color = state)) +
  facet_grid(. ~ response) +
   theme(legend.position = "bottom")
```

